name: Magisk Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.api }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        api: [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD test
        run: scripts/avd_test.sh ${{ matrix.api }}
